name: Create Branch
on:
  create
jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create new branch
      run: git checkout -b new-branch-${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
