name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    container: node:16
    steps:
    - uses: actions/checkout@v3
    - name: Generate docs
      run: doxygen Doxyfile
